export interface BackgroundTraits {
  personality: string[];
  ideals: string[];
  bonds: string[];
  flaws: string[];
}

export interface Background {
  key: string;
  name: string;
  description: string;
  skillProficiencies: string[];
  traits: BackgroundTraits;
}

export const BACKGROUNDS: Background[] = [
  {
    key: 'acolyte',
    name: 'Accolito',
    description: 'Hai trascorso la tua vita al servizio di un tempio.',
    skillProficiencies: ['insight', 'religion'],
    traits: {
      personality: [
        'Idolatro un particolare eroe del mio credo e mi riferisco continuamente alle sue gesta.',
        'Posso trovare terreno comune tra i nemici più accaniti, cercando sempre la pace.',
        'Vedo presagi ovunque e nelle opere degli dei.',
        'Nulla può scuotere la mia visione ottimistica.',
        'Cito le sacre scritture in ogni situazione, anche inappropriata.',
        'Sono tollerante (o intollerante) delle altre fedi.',
        'Ho goduto di cibo e vitto raffinati nel tempio. I disagi mi turbano molto.',
        'Mi aspetto di essere trattato bene in ogni situazione.',
      ],
      ideals: [
        'Tradizione. I riti e le preghiere dei miei antenati non devono mai essere dimenticati.',
        'Carità. Cerco sempre di aiutare chi è nel bisogno, indipendentemente dal costo personale.',
        'Cambiamento. I vecchi modi devono evolvere. Il mondo ha bisogno di rinnovamento.',
        'Potere. Spero di diventare un giorno un capo potente della mia religione.',
        'Fede. Confido che la mia divinità guidi le mie azioni.',
        'Aspirazione. Spero di compiere un grande sacrificio per la mia religione.',
      ],
      bonds: [
        'Darei la vita per recuperare un testo sacro rubato dal mio tempio.',
        'Ho venduto i miei beni per comprare la mia posizione nel tempio.',
        'Mi sono fidanzato/a con un membro di un tempio rivale.',
        'Sono il custode di un segreto antico della mia religione.',
        'Sto cercando un potente demonio che ha devastato il mio tempio.',
        'Cerco di proteggere un giovane chierico di cui mi sono preso cura.',
      ],
      flaws: [
        'Giudico gli altri con durezza, e me stesso ancora di più.',
        'Ripongo troppa fiducia negli ideali del mio tempio.',
        'La mia pietà mi rende spesso ingenuo.',
        'Sono inflessibile nel mio pensiero.',
        'Sospetto di tutti senza prove.',
        'Quando scelgo un obiettivo, divento ossessivo e trascuro tutto il resto.',
      ],
    },
  },
  {
    key: 'criminal',
    name: 'Criminale',
    description: 'Sei un esperto del crimine e hai connessioni con il mondo della mala.',
    skillProficiencies: ['deception', 'stealth'],
    traits: {
      personality: [
        'Ho sempre un piano per fuggire quando le cose si mettono male.',
        'Sono calmo in ogni situazione. Non ho mai alzato la voce o perso la freddhezza.',
        'Il primo denaro che guadagno va sempre al gioco.',
        'Preferisco rubare il necessario piuttosto che mendicare.',
        'Sono incredibilmente lento a fidarmi degli altri, e loro devono guadagnarsi la fiducia.',
        'Non mi importa uccidere, ma preferisco soluzioni non violente.',
        'Quando vedo qualcosa di bello voglio averlo.',
        'Sono sfrontato in modo provocatorio.',
      ],
      ideals: [
        'Onore. Non rubo da chi non può permetterselo.',
        'Libertà. Le catene devono essere spezzate, le persone non dovrebbero essere schiave.',
        'Carità. Rubo ai ricchi per dare ai poveri.',
        'Avidità. Faccio quello che faccio per i soldi, fine.',
        'Popolo. Mi preoccupo per le persone che conosco, non per regole astratte.',
        'Redenzione. C\'è luce in ogni cuore, anche in quello più oscuro.',
      ],
      bonds: [
        'Sto cercando di riscattarmi per qualcosa di terribile che ho fatto.',
        'Qualcuno che amo ha bisogno dei miei soldi.',
        'Vengo da un ghetto e ci tornerò per aiutare la mia gente.',
        'Qualcuno mi ha tradito e lo inseguirò fino ai confini del mondo.',
        'Sono colpevole di un crimine terribile che mi perseguita.',
        'Devo la mia posizione a un mentore e non permetterò che venga disonorato.',
      ],
      flaws: [
        'Quando vedo qualcosa di prezioso, non posso fare a meno di pensare come rubarla.',
        'Quando sono in pericolo scappo dal conflitto.',
        'Sono un giocatore incallito e non posso resistere a una scommessa.',
        'Sono arrogante e mi metto spesso in situazioni difficili.',
        'Mento compulsivamente, anche quando non serve.',
        'La violenza è la mia prima soluzione a ogni problema.',
      ],
    },
  },
  {
    key: 'folk_hero',
    name: 'Eroe del Popolo',
    description: 'Vieni da una famiglia di umili origini, ma sei destinato a qualcosa di grande.',
    skillProficiencies: ['animal_handling', 'survival'],
    traits: {
      personality: [
        'Giudico le persone per le loro azioni, non per le loro parole.',
        'Se qualcuno è nei guai, mi fermo ad aiutarlo.',
        'Quando mi prefiggo un obiettivo, non mi fermo davanti a nulla.',
        'Ho un forte senso del diritto e del torto.',
        'Sono testardo e faccio le cose a modo mio.',
        'Non mi fido di nessuno che non abbia lavorato sodo nella vita.',
        'Odio i nobili e i potenti che sfruttano la gente comune.',
        'Sono gentile con tutti e cerco di capire il punto di vista altrui.',
      ],
      ideals: [
        'Rispetto. Le persone meritano di essere trattate con dignità.',
        'Equità. Nessuno dovrebbe ricevere un trattamento speciale davanti alla legge.',
        'Libertà. I tiranni non devono vincolare le persone.',
        'Potere. Se divento forte, posso cambiare le cose.',
        'Sincerità. Non c\'è posto per le menzogne nella mia vita.',
        'Destino. Niente potrà fermarmi nel compiere il mio destino.',
      ],
      bonds: [
        'Ho una famiglia contadina e farei qualsiasi cosa per proteggerla.',
        'Un tiranno ha rovinato la mia vita. Lo sconfiggerò.',
        'Ho un vecchio mentore che continua a guidarmi.',
        'Ho giurato di proteggere il mio villaggio.',
        'Una persona che amavo è morta per colpa di un signore crudele.',
        'Devo dimostrare di valere qualcosa, di essere più dei miei umili natali.',
      ],
      flaws: [
        'Il tiranno che opprime il mio popolo mi ha sconfitto una volta.',
        'Sono convinto di essere invulnerabile.',
        'Non mi fido delle autorità.',
        'Sono lento nell\'imparare dai miei errori.',
        'Penso troppo in grande e non calcolo i rischi.',
        'Sono troppo orgoglioso per chiedere aiuto.',
      ],
    },
  },
  {
    key: 'noble',
    name: 'Nobile',
    description: 'Sei nato e cresciuto tra i privilegi dell\'aristocrazia.',
    skillProficiencies: ['history', 'persuasion'],
    traits: {
      personality: [
        'La mia eloquenza e fiducia in me stesso mettono a disagio gli altri.',
        'Ho bisogno di lusso e mi sento a disagio in condizioni spartane.',
        'Sono sempre educato, anche con i miei nemici.',
        'Non mi importa cosa pensano gli altri. La mia famiglia è nobile.',
        'Sono sicuro di poter convincere chiunque con le parole giuste.',
        'Non sopporto il disordine e tengo tutto perfettamente organizzato.',
        'Preferisco un accordo a una battaglia.',
        'Mi fido solo della famiglia. La politica è tradimento.',
      ],
      ideals: [
        'Rispetto. Il rispetto è dovuto a chi lo merita, non solo ai nobili.',
        'Responsabilità. Il mio dovere è proteggere chi dipende da me.',
        'Potere. Se sono al potere, posso fare del bene.',
        'Famiglia. Il sangue è più denso dell\'acqua.',
        'Nobiltà. Il mio casato deve continuare a prosperare.',
        'Anti-autorità. Il mio nobile titolo mi dà la libertà di fare ciò che voglio.',
      ],
      bonds: [
        'Devo proteggere il mio casato a ogni costo.',
        'Sono innamorato di qualcuno che la mia famiglia non approverebbe.',
        'La mia lealtà alla mia corona è incrollabile.',
        'Qualcuno ha cercato di rubarmi il titolo. Lo ricorderò.',
        'Le terre di famiglia sono sacre per me.',
        'Un mentore mi ha insegnato i valori della vera nobiltà.',
      ],
      flaws: [
        'Mi convinco facilmente di meritare posizioni di comando.',
        'Nascondo uno scandalo che potrebbe distruggere il mio casato.',
        'Nutro un segreto disprezzo per chi è di bassa estrazione.',
        'Sono abituato al lusso e mi lamento spesso dei disagi.',
        'Spendo soldi a profusione senza pensare alle conseguenze.',
        'Spesso dimentico che le persone comuni hanno una vita difficile.',
      ],
    },
  },
  {
    key: 'sage',
    name: 'Studioso',
    description: 'Hai trascorso anni a studiare in biblioteche e accademie.',
    skillProficiencies: ['arcana', 'history'],
    traits: {
      personality: [
        'Uso parole lunghe per dimostrare la mia intelligenza.',
        'Ho letto tutto in biblioteca e cito fonti in ogni conversazione.',
        'Sono abituato ad aiutare e a fare favori a chi mi chiede informazioni.',
        'Non ho problemi a portare sulle spalle il peso dell\'umanità.',
        'Non sono bravo con le persone, ma amo gli animali.',
        'Mi addormento facilmente durante gli eventi sociali e nelle guardie.',
        'Non conosco molto del mondo reale al di là dei libri.',
        'Uso il sarcasmo e l\'ironia per comunicare.',
      ],
      ideals: [
        'Conoscenza. Il sapere è il potere più grande.',
        'Bellezza. C\'è bellezza ovunque, basta cercarla.',
        'Logica. Le emozioni non devono offuscare il giudizio.',
        'Bene supremo. Uso la conoscenza per il bene di tutti.',
        'Auto-miglioramento. Mi sforzo sempre per imparare di più.',
        'Potere. La conoscenza è potere, e voglio tutto il potere.',
      ],
      bonds: [
        'Ho una raccolta di testi rari che proteggo a ogni costo.',
        'Lavoro per portare a termine la ricerca di un mentore defunto.',
        'Ho un rivale accademico che mi ha rubato il merito.',
        'Devo trovare una risposta a una domanda che mi ossessiona.',
        'Mi sono innamorato/a di qualcuno che non sa che esisto.',
        'La mia biblioteca è il mio castello.',
      ],
      flaws: [
        'Sono convinto di avere sempre ragione.',
        'Cito fonti inesistenti quando non conosco la risposta.',
        'Dimentico facilmente nomi, volti e accordi presi.',
        'Rimango bloccato in questioni irrisolvibili.',
        'Sono arrogante riguardo alla mia intelligenza.',
        'Non so dire di no a chi mi chiede aiuto per imparare.',
      ],
    },
  },
  {
    key: 'soldier',
    name: 'Soldato',
    description: 'Hai combattuto in guerra e ne porti le cicatrici.',
    skillProficiencies: ['athletics', 'intimidation'],
    traits: {
      personality: [
        'Sono sempre educato e rispettoso verso chi è in autorità.',
        'Sono perseguitato dai ricordi della guerra e dormo male.',
        'Sono lento a fare amicizia, ma leale fino alla morte.',
        'Quando non sono in combattimento, bevo o cerco altri intrattenimenti.',
        'Il più bello scherzo mi diverte come quello peggiore.',
        'Affronto i problemi direttamente e mi aspetto gli stessi in cambio.',
        'Sono abituato all\'obbedienza e mi è difficile agire da solo.',
        'Ho perso amici preziosi e faccio fatica a legarmi di nuovo.',
      ],
      ideals: [
        'Bene supremo. Il nostro destino è difendere il debole.',
        'Responsabilità. Faccio il mio dovere e basta.',
        'Indipendenza. Quando la gente segue gli ordini ciecamente, è il chaos.',
        'Forza. La vita è dura e devi essere duro per sopravvivere.',
        'Gloria. Devo guadagnare gloria nel campo di battaglia.',
        'Nazione. La mia città, il mio popolo, il mio signore — questo è tutto.',
      ],
      bonds: [
        'Morirei per l\'unità con cui ho servito.',
        'Qualcuno ha salvato la mia vita sul campo di battaglia. Devo ripagarlo.',
        'Il mio onore è tutto ciò che ho. Non lo tradirò.',
        'Sto cercando di dimenticare un errore terribile commesso in guerra.',
        'Amo qualcuno che non rivedrò forse mai.',
        'Qualcuno che ho amato è morto al mio posto.',
      ],
      flaws: [
        'Il mostro che emerge in battaglia è difficile da spegnere.',
        'Odio amaro verso il nemico mi porta ad atti di crudeltà.',
        'Non mi fido degli ordini se non conosco chi li dà.',
        'Bevo troppo per dimenticare.',
        'Ho subito dei traumi e mi metto in pericolo inutilmente.',
        'Penso solo in termini militari e non capisco le situazioni sociali.',
      ],
    },
  },
  {
    key: 'outlander',
    name: 'Straniero',
    description: 'Sei cresciuto nella natura selvaggia, lontano dalla civiltà.',
    skillProficiencies: ['athletics', 'survival'],
    traits: {
      personality: [
        'Sono guidato da un forte senso di equità.',
        'Proteggo i miei compagni come proteggo i miei.',
        'Non capisco i modi della civiltà e faccio gaffe sociali.',
        'Sono facilmente distratto dalla bellezza della natura.',
        'Parlo poco, ma quando parlo dico sempre qualcosa di importante.',
        'Devo sempre sapere dove sono le uscite in ogni stanza.',
        'Mangio come un animale affamato e ho pochi modi a tavola.',
        'Dormo meglio all\'aperto che sotto un tetto.',
      ],
      ideals: [
        'Cambiamento. La vita è come le stagioni: in continuo mutamento.',
        'Bene supremo. È mio dovere prendermi cura degli altri.',
        'Onore. Non mento mai, anche se la verità fa male.',
        'Potere della natura. La natura è la forza più grande che esista.',
        'Gloria. Devo dimostrare il mio valore attraverso le imprese.',
        'Vivere pienamente. Ogni giorno è un dono.',
      ],
      bonds: [
        'La mia famiglia è la cosa più preziosa per me.',
        'Devo molta fedeltà alla mia tribù.',
        'Ho incontrato un essere potente nella natura e lo servo.',
        'Proteggo sempre il territorio da cui vengo.',
        'Cerco un mentore perduto.',
        'Voglio vendicare la mia tribù decimata.',
      ],
      flaws: [
        'Non ho stima per il lusso e li disprezzo in chi li possiede.',
        'Non sono adatto alla vita in città e mi confondo facilmente.',
        'Ricordo sempre il mio territorio come se fosse paradiso.',
        'Non capisco i concetti di proprietà privata.',
        'Sono violento quando qualcuno mi sfida.',
        'Ho paura della magia che non capisco.',
      ],
    },
  },
  {
    key: 'entertainer',
    name: 'Intrattenitore',
    description: 'Sei cresciuto sul palcoscenico, sapendo come affascinare il pubblico.',
    skillProficiencies: ['acrobatics', 'performance'],
    traits: {
      personality: [
        'Conosco molte storie e ne invento di nuove quando quelle note finiscono.',
        'Quando mi annoio, cerco sempre qualcosa di eccitante.',
        'Mi piace stare al centro dell\'attenzione.',
        'Sono portato all\'eccesso: mangio troppo, bevo troppo, rido troppo.',
        'Mi adatto facilmente a qualsiasi tipo di persone.',
        'Cambio facilmente umore: sono gioioso e poi malinconico.',
        'Sono molto generoso con i miei complimenti.',
        'Mi piace intrattenere anche nelle situazioni peggiori.',
      ],
      ideals: [
        'Bellezza. Quando creo qualcosa di bello, il mondo migliora.',
        'Tradizione. I canti e le storie degli antenati devono sopravvivere.',
        'Creatività. Il mondo ha bisogno di novità, non di tradizione.',
        'Libertà. Canzoni e storie liberano l\'anima.',
        'Bene supremo. Arte per tutti, non solo per i ricchi.',
        'Sincerità. L\'arte che mente non è vera arte.',
      ],
      bonds: [
        'Il mio strumento musicale è tutto ciò che ho del mio passato.',
        'Devo qualcosa a un mecenate che mi ha aiutato.',
        'Voglio vendicare un torto subito da un rivale.',
        'Ho un rivale segreto che vuole distruggermi.',
        'Devo proteggere qualcuno che mi ha dato rifugio.',
        'Voglio portare la mia arte nel mondo intero.',
      ],
      flaws: [
        'Faccio di tutto per essere il centro dell\'attenzione.',
        'Non posso resistere a scommettere.',
        'Mi innamoro troppo in fretta.',
        'Bevo troppo quando sono nervoso.',
        'Sono facilmente geloso del successo altrui.',
        'Dico quello che la gente vuole sentire, non la verità.',
      ],
    },
  },
  {
    key: 'hermit',
    name: 'Eremita',
    description: 'Hai vissuto in isolamento, cercando la verità nella solitudine.',
    skillProficiencies: ['medicine', 'religion'],
    traits: {
      personality: [
        'Sono abituato al silenzio e mi disturba il rumore.',
        'Sono pacifico e cerco sempre soluzioni pacifiche.',
        'Sono curioso del mondo dopo anni di isolamento.',
        'Conosco un segreto che nessun altro conosce.',
        'Mi dimentico facilmente di mangiare e dormire quando sono concentrato.',
        'Sono gentile e premuroso con tutti.',
        'Non mi interessa la ricchezza materiale.',
        'Trovo la bellezza nelle cose semplici.',
      ],
      ideals: [
        'Bene supremo. Il mio isolamento mi ha insegnato a capire la sofferenza.',
        'Logica. Le emozioni offuscano la verità.',
        'Bellezza. Vedo la bellezza in ogni essere.',
        'Libero pensiero. L\'indagine è alla base di ogni progresso.',
        'Potere. La solitudine mi ha reso forte.',
        'Vivere pienamente. Dopo anni di isolamento, voglio vivere ogni momento.',
      ],
      bonds: [
        'Cerco la risposta a una grande domanda cosmica.',
        'Voglio condividere la saggezza che ho trovato nella solitudine.',
        'Qualcuno che amavo è morto, e la solitudine era il mio lutto.',
        'Il luogo dove ho vissuto è sacro per me.',
        'Ho visto una visione profetica che mi guida.',
        'Devo proteggere un segreto che ho scoperto.',
      ],
      flaws: [
        'Ora che sono nel mondo, sono facilmente sopraffatto dalle persone.',
        'Non ho pazienza per chi cede ai vizi.',
        'Sono convinto di aver trovato la verità e gli altri hanno torto.',
        'Non so come interagire socialmente.',
        'Sono ossessionato da una verità che potrebbe essere pericolosa.',
        'Non mi fido di nessuno.',
      ],
    },
  },
  {
    key: 'urchin',
    name: 'Monello',
    description: 'Sei cresciuto per le strade, imparando a sopravvivere senza nessuno.',
    skillProficiencies: ['sleight_of_hand', 'stealth'],
    traits: {
      personality: [
        'Nascondo il cibo per abitudine, anche quando non ne ho bisogno.',
        'Mi fido degli emarginati prima che degli aristocratici.',
        'Non mi è mai importato cosa pensassero gli altri di me.',
        'Quando devo scegliere tra amicizia e oro, scelgo l\'oro.',
        'Sono gentile con chi ha avuto una vita difficile come me.',
        'Sembro sempre pronto a fuggire.',
        'Uso soprannomi per tutti.',
        'Sono ingenuo riguardo alle norme sociali dei ricchi.',
      ],
      ideals: [
        'Rispetto. Tutti meritano rispetto, ricchi o poveri.',
        'Comunità. Dobbiamo prenderci cura gli uni degli altri.',
        'Cambiamento. Le diseguaglianze devono finire.',
        'Redenzione. Voglio dimostrare che chi nasce povero può fare grandi cose.',
        'Persone. Mi preoccupo per chi conosco, non per le norme.',
        'Aspirazione. Un giorno avrò tutto quello che non ho mai avuto.',
      ],
      bonds: [
        'Il mio quartiere di provenienza è la mia famiglia.',
        'Devo qualcosa a una persona che mi ha aiutato quando ero senza casa.',
        'Ho un rivale nei bassifondi che vuole vedermi morto.',
        'Sto cercando il mio fratello o sorella da cui sono stato/a separato/a.',
        'Voglio diventare ricco per non soffrire mai più.',
        'Proteggo sempre i bambini di strada.',
      ],
      flaws: [
        'Rubo da chi ha più di me, giustificandomi.',
        'Non sono abituato alla gentilezza e mi mette a disagio.',
        'Non so chiedere aiuto: è una debolezza.',
        'Sono crudele con chi ha avuto vita facile.',
        'Sto sempre cercando di capire come guadagnare dalla situazione.',
        'Non mi fido di nessuno abbastanza da affidarmi a loro.',
      ],
    },
  },
];

export function getBackground(key: string): Background | undefined {
  return BACKGROUNDS.find(b => b.key === key);
}

export function rollTrait(traits: string[]): string {
  return traits[Math.floor(Math.random() * traits.length)];
}
