export interface SrdSpell {
  id: string;           // kebab-case English key, e.g. "fireball"
  name: string;         // Italian name
  level: number;        // 0 = cantrip
  school: string;       // lowercase English: "abjuration"|"conjuration"|"divination"|"enchantment"|"evocation"|"illusion"|"necromancy"|"transmutation"
  classes: string[];    // from: 'bard'|'cleric'|'druid'|'paladin'|'ranger'|'sorcerer'|'warlock'|'wizard'
  concentration: boolean;
  ritual: boolean;
  castingTime: string;  // Italian
  range: string;        // Italian
  duration: string;     // Italian
  components: string;
  description: string;  // Italian mechanical description, 1-3 sentences
}

export const SCHOOLS_IT: Record<string, string> = {
  abjuration: 'Abiurazione',
  conjuration: 'Evocazione',
  divination: 'Divinazione',
  enchantment: 'Ammaliamento',
  evocation: 'Invocazione',
  illusion: 'Illusione',
  necromancy: 'Necromanzia',
  transmutation: 'Trasmutazione',
};

export const SRD_SPELLS: SrdSpell[] = [
  // ─── CANTRIPS (level 0) ───────────────────────────────────────────────────

  {
    id: 'dardo-di-fuoco',
    name: 'Dardo di Fuoco',
    level: 0,
    school: 'evocation',
    classes: ['wizard', 'sorcerer'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '27 m',
    duration: 'Istantanea',
    components: 'V, S',
    description:
      'Lanci un piccolo dardo di fuoco verso una creatura o un oggetto entro gittata. Il bersaglio subisce 1d10 danni da fuoco. I danni aumentano di 1d10 al 5°, 11° e 17° livello.',
  },
  {
    id: 'raggio-di-gelo',
    name: 'Raggio di Gelo',
    level: 0,
    school: 'evocation',
    classes: ['wizard', 'sorcerer'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '18 m',
    duration: 'Istantanea',
    components: 'V, S',
    description:
      'Un raggio di energia glaciale si proietta verso una creatura entro gittata; effettua un attacco a distanza con incantesimo. In caso di colpo, il bersaglio subisce 1d8 danni da freddo e la sua velocità si riduce di 3 m fino all\'inizio del tuo turno successivo. I danni aumentano di 1d8 al 5°, 11° e 17° livello.',
  },
  {
    id: 'fiamma-sacra',
    name: 'Fiamma Sacra',
    level: 0,
    school: 'evocation',
    classes: ['cleric'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '18 m',
    duration: 'Istantanea',
    components: 'V, S',
    description:
      'Una luce simile a una fiamma discende su una creatura che puoi vedere entro gittata. Il bersaglio deve superare un TPS Destrezza o subire 1d8 danni radianti; i coperti non danno vantaggio a questo tiro. I danni aumentano di 1d8 al 5°, 11° e 17° livello.',
  },
  {
    id: 'presa-folgorante',
    name: 'Presa Folgorante',
    level: 0,
    school: 'evocation',
    classes: ['wizard', 'sorcerer'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione',
    range: '9 m',
    duration: 'Concentrazione, fino a 1 minuto',
    components: 'V, S',
    description:
      'Crei un filo di folgore che colpisce una creatura entro gittata; effettua un attacco a distanza con incantesimo. In caso di colpo, il bersaglio subisce 1d8 danni da fulmine ed è trattenuto finché mantieni la concentrazione; alla fine di ogni suo turno può effettuare un TPS Forza per liberarsi. I danni aumentano di 1d8 al 5°, 11° e 17° livello.',
  },
  {
    id: 'proiettile-occulto',
    name: 'Proiettile Occulto',
    level: 0,
    school: 'evocation',
    classes: ['warlock'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '36 m',
    duration: 'Istantanea',
    components: 'V, S',
    description:
      'Lanci un raggio di energia occulta verso una creatura che puoi vedere entro gittata; effettua un attacco a distanza con incantesimo. In caso di colpo, il bersaglio subisce 1d10 danni da forza. I danni aumentano di 1d10 al 5°, 11° e 17° livello.',
  },
  {
    id: 'mano-del-mago',
    name: 'Mano del Mago',
    level: 0,
    school: 'conjuration',
    classes: ['wizard', 'sorcerer', 'warlock', 'bard'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '9 m',
    duration: '1 minuto',
    components: 'V, S',
    description:
      'Evochi una mano spettrale fluttuante entro gittata che persiste per la durata. Puoi usare un\'azione bonus per controllare la mano e farle manipolare oggetti, aprire porte o contenitori non chiusi a chiave, riporre o recuperare oggetti, o versare liquidi; non può attaccare né trasportare più di 5 kg.',
  },
  {
    id: 'prestidigitazione',
    name: 'Prestidigitazione',
    level: 0,
    school: 'transmutation',
    classes: ['wizard', 'sorcerer', 'warlock', 'bard'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '3 m',
    duration: '1 ora',
    components: 'V, S',
    description:
      'Produco uno dei tanti effetti magici minori entro gittata: creare un effetto sensoriale innocuo, accendere o spegnere una fiamma, pulire o sporcare un oggetto, raffreddare o riscaldare materiale non vivente, creare un piccolo simbolo o marchio, o produrre una bagatella magica. Ogni effetto singolo dura fino a 1 ora, ad eccezione degli effetti istantanei.',
  },
  {
    id: 'illusione-minore',
    name: 'Illusione Minore',
    level: 0,
    school: 'illusion',
    classes: ['wizard', 'sorcerer', 'warlock', 'bard'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '9 m',
    duration: '1 minuto',
    components: 'S, M (un po\' di lana di pecora)',
    description:
      'Crei un suono o un\'immagine illusoria entro gittata che persiste per la durata. Un\'immagine non può essere più grande di un cubo di 1,5 m. Una creatura che usa la sua azione per esaminare l\'illusione può capire che è falsa con un tiro di Indagare (Intelligenza) contro la tua CD dell\'incantesimo.',
  },
  {
    id: 'guida',
    name: 'Guida',
    level: 0,
    school: 'divination',
    classes: ['cleric', 'druid'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione',
    range: 'Tocco',
    duration: 'Concentrazione, fino a 1 minuto',
    components: 'V, S',
    description:
      'Tocchi una creatura consenziente. Una volta prima che l\'incantesimo termini, il bersaglio può tirare un d4 e aggiungere il risultato a un tiro di caratteristica a sua scelta.',
  },
  {
    id: 'resistenza',
    name: 'Resistenza',
    level: 0,
    school: 'abjuration',
    classes: ['cleric', 'druid'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione',
    range: 'Tocco',
    duration: 'Concentrazione, fino a 1 minuto',
    components: 'V, S, M (un mantello miniatura)',
    description:
      'Tocchi una creatura consenziente. Una volta prima che l\'incantesimo termini, il bersaglio può tirare un d4 e aggiungere il risultato a un tiro salvezza a sua scelta.',
  },
  {
    id: 'taumaturgia',
    name: 'Taumaturgia',
    level: 0,
    school: 'transmutation',
    classes: ['cleric'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '9 m',
    duration: '1 minuto',
    components: 'V',
    description:
      'Manifesti un piccolo prodigio, un segno del potere soprannaturale. Puoi produrre uno dei seguenti effetti a tua scelta: la tua voce rimbomba fino a tre volte il suo volume normale, le fiamme tremolano e cambiano colore, tremori innocui si diffondono sul terreno, un forte rumore simile al tuono rimbomba, i tuoi occhi brillano, oppure apri o chiudi porte o finestre.',
  },
  {
    id: 'insulto-vile',
    name: 'Insulto Vile',
    level: 0,
    school: 'enchantment',
    classes: ['bard'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '18 m',
    duration: 'Istantanea',
    components: 'V',
    description:
      'Pronunci un insulto intriso di magia verso una creatura che puoi vedere entro gittata. Se la creatura riesce a sentirti, deve superare un TPS Carisma o subire 1d6 danni psichici. I danni aumentano di 1d6 al 5°, 11° e 17° livello.',
  },
  {
    id: 'arte-dei-druidi',
    name: 'Arte dei Druidi',
    level: 0,
    school: 'transmutation',
    classes: ['druid'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '9 m',
    duration: 'Istantanea',
    components: 'V, S',
    description:
      'Sussurri i segreti della natura a piante e animali entro gittata, producendo uno dei seguenti effetti: creare fiori e foglie non tossiche o frutti innocui, creare un effetto sensoriale naturale come la pioggia, il vento o lo sciabordio dell\'acqua, oppure accendere o spegnere una piccola fiamma.',
  },
  {
    id: 'produrre-fiamma',
    name: 'Produrre Fiamma',
    level: 0,
    school: 'conjuration',
    classes: ['druid'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: 'Sé stesso',
    duration: '10 minuti',
    components: 'V, S',
    description:
      'Una fiamma senza fumo appare nella tua mano aperta e vi rimane per la durata, illuminando luce intensa per 3 m e luce fioca per altri 3 m. Come azione puoi scagliare la fiamma verso una creatura entro 9 m: effettua un attacco a distanza con incantesimo; in caso di colpo il bersaglio subisce 1d8 danni da fuoco. I danni aumentano di 1d8 al 5°, 11° e 17° livello.',
  },
  {
    id: 'luce',
    name: 'Luce',
    level: 0,
    school: 'evocation',
    classes: ['wizard', 'cleric', 'bard', 'sorcerer'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: 'Tocco',
    duration: '1 ora',
    components: 'V, M (un fungo fosforescente o una lucciola)',
    description:
      'Tocchi un oggetto non più grande di 3 m in ogni sua dimensione. Esso irradia luce intensa per 6 m e luce fioca per altri 6 m. Se tocci una creatura ostile deve superare un TPS Destrezza per evitare l\'effetto. L\'incantesimo termina se lo lanci di nuovo o lo dissolvi con un\'azione.',
  },
  {
    id: 'tocco-gelido',
    name: 'Tocco Gelido',
    level: 0,
    school: 'necromancy',
    classes: ['wizard', 'sorcerer', 'warlock'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '9 m',
    duration: '1 round',
    components: 'V, S',
    description:
      'Crei una mano spettrale scheletrica entro gittata; effettua un attacco a distanza con incantesimo. In caso di colpo il bersaglio subisce 1d8 danni necrotici e non può recuperare punti ferita fino all\'inizio del tuo prossimo turno; se il bersaglio è un non-morto ha anche svantaggio ai tiri per colpire contro di te fino alla fine del tuo prossimo turno. I danni aumentano di 1d8 al 5°, 11° e 17° livello.',
  },

  // ─── LEVEL 1 ─────────────────────────────────────────────────────────────

  {
    id: 'dardo-incantato',
    name: 'Dardo Incantato',
    level: 1,
    school: 'evocation',
    classes: ['wizard', 'sorcerer'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '27 m',
    duration: 'Istantanea',
    components: 'V, S',
    description:
      'Crei tre dardi luminosi di forza magica che colpiscono automaticamente altrettante creature o la stessa a tua scelta, entro gittata, ciascuno per 1d4+1 danni da forza. Per ogni slot di livello superiore al 1° lanci un dardo aggiuntivo.',
  },
  {
    id: 'scudo',
    name: 'Scudo',
    level: 1,
    school: 'abjuration',
    classes: ['wizard', 'sorcerer'],
    concentration: false,
    ritual: false,
    castingTime: '1 reazione, che usi quando vieni colpito da un attacco o colpito da Dardo Incantato',
    range: 'Sé stesso',
    duration: '1 round',
    components: 'V, S',
    description:
      'Un\'invisibile barriera di forza magica appare e ti protegge. Fino all\'inizio del tuo prossimo turno ottieni +5 alla CA, anche contro l\'attacco scatenante, e non subisci danni da Dardo Incantato.',
  },
  {
    id: 'mani-brucianti',
    name: 'Mani Brucianti',
    level: 1,
    school: 'evocation',
    classes: ['wizard', 'sorcerer'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: 'Sé stesso (cono di 4,5 m)',
    duration: 'Istantanea',
    components: 'V, S',
    description:
      'Un cono di fiamme di 4,5 m scaturisce dalle tue mani. Ogni creatura nel cono deve effettuare un TPS Destrezza, subendo 3d6 danni da fuoco in caso di fallimento, o la metà in caso di successo. Per ogni slot di livello superiore al 1° i danni aumentano di 1d6.',
  },
  {
    id: 'ammaliare-persone',
    name: 'Ammaliare Persone',
    level: 1,
    school: 'enchantment',
    classes: ['wizard', 'sorcerer', 'warlock', 'bard', 'druid'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '9 m',
    duration: '1 ora',
    components: 'V, S',
    description:
      'Tenti di ammaliare un umanoide che puoi vedere entro gittata. Il bersaglio deve effettuare un TPS Saggezza; se lo fallisce è ammaliato da te fino al termine della durata o finché non gli arrechi danni o lo minacci. Il bersaglio ammaliato ti considera un amico fidato. Puoi bersagliare una creatura aggiuntiva per ogni slot di livello superiore al 1°.',
  },
  {
    id: 'cura-ferite',
    name: 'Cura Ferite',
    level: 1,
    school: 'evocation',
    classes: ['cleric', 'druid', 'paladin', 'ranger', 'bard'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: 'Tocco',
    duration: 'Istantanea',
    components: 'V, S',
    description:
      'Una creatura che tocchi recupera 1d8 + modificatore di caratteristica da incantesimo punti ferita. Non funziona sui non-morti o sui costrutti. Per ogni slot di livello superiore al 1° guarisce 1d8 PF aggiuntivi.',
  },
  {
    id: 'parola-guaritrice',
    name: 'Parola Guaritrice',
    level: 1,
    school: 'evocation',
    classes: ['cleric', 'druid', 'bard'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione bonus',
    range: '18 m',
    duration: 'Istantanea',
    components: 'V',
    description:
      'Una creatura che puoi vedere entro gittata recupera 1d4 + modificatore di caratteristica da incantesimo punti ferita. Non funziona sui non-morti o sui costrutti. Per ogni slot di livello superiore al 1° guarisce 1d4 PF aggiuntivi.',
  },
  {
    id: 'scudo-della-fede',
    name: 'Scudo della Fede',
    level: 1,
    school: 'abjuration',
    classes: ['cleric', 'paladin'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione bonus',
    range: '18 m',
    duration: 'Concentrazione, fino a 10 minuti',
    components: 'V, S, M (un piccolo foglio di pergamena con un testo sacro)',
    description:
      'Un campo luminoso avvolge una creatura a tua scelta entro gittata, aumentandone la CA di +2 per la durata dell\'incantesimo.',
  },
  {
    id: 'benedizione',
    name: 'Benedizione',
    level: 1,
    school: 'enchantment',
    classes: ['cleric', 'paladin'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione',
    range: '9 m',
    duration: 'Concentrazione, fino a 1 minuto',
    components: 'V, S, M (un po\' di acqua santa)',
    description:
      'Benedici fino a tre creature a tua scelta entro gittata. Ogni volta che un bersaglio effettua un tiro per colpire o un tiro salvezza prima che l\'incantesimo termini, può tirare un d4 e aggiungere il risultato. Per ogni slot di livello superiore al 1° puoi bersagliare una creatura aggiuntiva.',
  },
  {
    id: 'sonno',
    name: 'Sonno',
    level: 1,
    school: 'enchantment',
    classes: ['wizard', 'sorcerer', 'bard'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '27 m',
    duration: '1 minuto',
    components: 'V, S, M (una presa di sabbia fine, petali di rosa o un grillo)',
    description:
      'Invii le creature in un sonno magico: tira 5d8 per ottenere il totale di PF che puoi addormentare. Le creature entro 6 m dal punto scelto vengono colpite in ordine crescente di PF attuali (iniziando dalla più debole), ignorando i non-morti e le creature immuni agli effetti di ammaliamento. Per ogni slot superiore al 1° il totale aumenta di 2d8.',
  },
  {
    id: 'onda-tonante',
    name: 'Onda Tonante',
    level: 1,
    school: 'evocation',
    classes: ['wizard', 'sorcerer', 'druid', 'bard'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: 'Sé stesso (cubo di 4,5 m)',
    duration: 'Istantanea',
    components: 'V, S',
    description:
      'Un\'onda di forza tuonante si diffonde in un cubo di 4,5 m a partire da te. Ogni creatura nel cubo deve effettuare un TPS Costituzione, subendo 2d8 danni da tuono e venendo spinta di 3 m in caso di fallimento, o solo la metà dei danni senza spinta in caso di successo. Per ogni slot superiore al 1° i danni aumentano di 1d8.',
  },
  {
    id: 'armatura-del-mago',
    name: 'Armatura del Mago',
    level: 1,
    school: 'abjuration',
    classes: ['wizard', 'sorcerer'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: 'Tocco',
    duration: '8 ore',
    components: 'V, S, M (un pezzo di cuoio conciato)',
    description:
      'Tocchi una creatura consenziente che non indossa armatura. La sua CA diventa 13 + modificatore di Destrezza finché l\'incantesimo è attivo. L\'incantesimo termina se la creatura indossa un\'armatura.',
  },
  {
    id: 'maledizione',
    name: 'Maledizione',
    level: 1,
    school: 'enchantment',
    classes: ['warlock', 'bard'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione bonus',
    range: '27 m',
    duration: 'Concentrazione, fino a 1 ora',
    components: 'V, S, M (l\'occhio conservato di un trilobite)',
    description:
      'Maledici una creatura che puoi vedere entro gittata. Scegli una caratteristica: il bersaglio ha svantaggio ai tiri di caratteristica con quella caratteristica. Inoltre, quando colpisci il bersaglio con un attacco aggiungi 1d6 danni necrotici. La durata aumenta con slot di livello superiore: 8 ore al 3°, 24 ore al 5°, permanente al 7°.',
  },
  {
    id: 'segno-del-cacciatore',
    name: 'Segno del Cacciatore',
    level: 1,
    school: 'divination',
    classes: ['ranger'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione bonus',
    range: '27 m',
    duration: 'Concentrazione, fino a 1 ora',
    components: 'V',
    description:
      'Scegli una creatura che puoi vedere entro gittata e la marchi come tua preda. Ottieni vantaggio ai tiri di Percezione e Sopravvivenza per trovarla, e infliggi 1d6 danni aggiuntivi del tipo dell\'arma ogni volta che la colpisci con un attacco. La durata aumenta con slot di livello superiore: 8 ore al 3°, 24 ore al 5°.',
  },
  {
    id: 'intralciare',
    name: 'Intralciare',
    level: 1,
    school: 'conjuration',
    classes: ['druid', 'ranger'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione',
    range: '27 m',
    duration: 'Concentrazione, fino a 1 minuto',
    components: 'V, S',
    description:
      'Erbe e liane si tendono attorno a tutte le creature a tua scelta in un\'area di 6 m di raggio entro gittata. Ogni creatura nell\'area deve superare un TPS Forza o essere trattenuta finché l\'incantesimo è attivo. Una creatura trattenuta può usare la sua azione per effettuare un TPS Forza per liberarsi.',
  },
  {
    id: 'favore-divino',
    name: 'Favore Divino',
    level: 1,
    school: 'evocation',
    classes: ['paladin'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione bonus',
    range: 'Sé stesso',
    duration: 'Concentrazione, fino a 1 minuto',
    components: 'V, S',
    description:
      'Le tue armi risplendono di luce divina. Fino al termine della durata, i tuoi attacchi con arma infliggono 1d4 danni radianti aggiuntivi ad ogni colpo.',
  },
  {
    id: 'finta-vitalita',
    name: 'Finta Vitalità',
    level: 1,
    school: 'necromancy',
    classes: ['wizard', 'sorcerer'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: 'Sé stesso',
    duration: '1 ora',
    components: 'V, S, M (un po\' di alcol o acqua di vita)',
    description:
      'Attingi a energie necromantiche oscure per guadagnare 1d4 + 4 punti ferita temporanei per la durata. Per ogni slot di livello superiore al 1° guadagni 5 PF temporanei aggiuntivi.',
  },
  {
    id: 'parola-di-comando',
    name: 'Parola di Comando',
    level: 1,
    school: 'enchantment',
    classes: ['cleric', 'paladin'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '18 m',
    duration: '1 round',
    components: 'V',
    description:
      'Pronunci un comando di una sola parola a una creatura che puoi vedere entro gittata. Il bersaglio deve superare un TPS Saggezza o seguire il comando nel suo turno successivo. Comandi tipici: avvicinarsi, fuggire, inginocchiarsi, lasciare (un oggetto), fermarsi. Per ogni slot superiore al 1° puoi bersagliare una creatura aggiuntiva.',
  },
  {
    id: 'caduta-morbida',
    name: 'Caduta Morbida',
    level: 1,
    school: 'transmutation',
    classes: ['wizard', 'sorcerer', 'bard', 'druid', 'ranger'],
    concentration: false,
    ritual: false,
    castingTime: '1 reazione, che usi quando tu o una creatura entro 18 m cadete',
    range: '18 m',
    duration: '1 minuto',
    components: 'V, M (una piccola piuma o un po\' di pelliccia di topo)',
    description:
      'Scegli fino a cinque creature in caduta entro gittata. La velocità di discesa si riduce a 18 m per round fino al termine della durata. Se la creatura atterra prima della fine dell\'incantesimo non subisce danni da caduta.',
  },
  {
    id: 'individuare-magia',
    name: 'Individuare Magia',
    level: 1,
    school: 'divination',
    classes: ['wizard', 'sorcerer', 'cleric', 'druid', 'bard', 'paladin', 'ranger'],
    concentration: true,
    ritual: true,
    castingTime: '1 azione',
    range: 'Sé stesso',
    duration: 'Concentrazione, fino a 10 minuti',
    components: 'V, S',
    description:
      'Per la durata percepisci la presenza di qualsiasi magia entro 9 m. Se percepisci magia puoi usare la tua azione per vedere un\'aura tenue attorno a ogni oggetto o creatura magici visibili nell\'area e conoscere la scuola di magia se esiste.',
  },
  {
    id: 'trovare-famiglio',
    name: 'Trovare un Famiglio',
    level: 1,
    school: 'conjuration',
    classes: ['wizard'],
    concentration: false,
    ritual: true,
    castingTime: '1 ora',
    range: '3 m',
    duration: 'Istantanea',
    components: 'V, S, M (carbone, incenso e erbe per un valore di 10 mo bruciate in un braciere di ottone)',
    description:
      'Ottieni il servizio di un famiglio, uno spirito che assume la forma di una creatura di tua scelta (corvo, gatto, serpente, ecc.). Il famiglio agisce indipendentemente ma obbedisce ai tuoi comandi; puoi vedere attraverso i suoi sensi e comunicare telepaticamente con esso entro 30 m.',
  },
  {
    id: 'infliggere-ferite',
    name: 'Infliggere Ferite',
    level: 1,
    school: 'necromancy',
    classes: ['cleric'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: 'Tocco',
    duration: 'Istantanea',
    components: 'V, S',
    description:
      'Effettua un attacco in mischia con incantesimo contro una creatura che puoi raggiungere. In caso di colpo infliggi 3d10 danni necrotici. Per ogni slot di livello superiore al 1° i danni aumentano di 1d10.',
  },
  {
    id: 'cura-ferite-animali',
    name: 'Guarire gli Animali',
    level: 1,
    school: 'divination',
    classes: ['druid', 'ranger'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: 'Tocco',
    duration: 'Istantanea',
    components: 'V, S',
    description:
      'Tocchi una bestia e questa recupera 2d8 + modificatore di caratteristica da incantesimo punti ferita. Per ogni slot di livello superiore al 1° la guarigione aumenta di 1d8.',
  },

  // ─── LEVEL 2 ─────────────────────────────────────────────────────────────

  {
    id: 'passo-fatato',
    name: 'Passo Fatato',
    level: 2,
    school: 'conjuration',
    classes: ['wizard', 'sorcerer', 'warlock', 'bard'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione bonus',
    range: '9 m',
    duration: 'Istantanea',
    components: 'V',
    description:
      'Ti teletrasporti in uno spazio non occupato che puoi vedere entro 9 m. Al 3° livello puoi portare con te una creatura consenziente di taglia Piccola o Umana, e così via per slot superiori (una creatura aggiuntiva per ogni due livelli sopra il 2°).',
  },
  {
    id: 'invisibilita',
    name: 'Invisibilità',
    level: 2,
    school: 'illusion',
    classes: ['wizard', 'sorcerer', 'warlock', 'bard'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione',
    range: 'Tocco',
    duration: 'Concentrazione, fino a 1 ora',
    components: 'V, S, M (un ciuffo di ciglia di pipistrello e una cipolla in foglia)',
    description:
      'Una creatura che tocchi diventa invisibile per la durata. Qualsiasi cosa la creatura indossi o trasporti è invisibile finché viene portata. L\'incantesimo termina per un bersaglio che effettua un attacco o lancia un incantesimo. Per ogni slot superiore al 2° puoi bersagliare una creatura aggiuntiva.',
  },
  {
    id: 'raggio-rovente',
    name: 'Raggio Rovente',
    level: 2,
    school: 'evocation',
    classes: ['wizard', 'sorcerer'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '36 m',
    duration: 'Istantanea',
    components: 'V, S',
    description:
      'Crei tre raggi di fuoco e li scagli verso bersagli entro gittata; puoi dirigerli verso lo stesso bersaglio o verso bersagli diversi. Per ogni raggio effettua un attacco a distanza con incantesimo; in caso di colpo il bersaglio subisce 2d6 danni da fuoco. Per ogni slot superiore al 2° crei un raggio aggiuntivo.',
  },
  {
    id: 'immagine-speculare',
    name: 'Immagine Speculare',
    level: 2,
    school: 'illusion',
    classes: ['wizard', 'sorcerer', 'warlock', 'bard'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: 'Sé stesso',
    duration: '1 minuto',
    components: 'V, S',
    description:
      'Compaiono tre copie illusorie di te stesso nello spazio che occupi. Ogni volta che una creatura ti attacca si tira un d20: con 6 o più, l\'attacco bersaglia una copia (che poi scompare). La CA delle copie è 10 + modificatore di Destrezza.',
  },
  {
    id: 'ragnatela',
    name: 'Ragnatela',
    level: 2,
    school: 'conjuration',
    classes: ['wizard', 'sorcerer'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione',
    range: '18 m',
    duration: 'Concentrazione, fino a 1 ora',
    components: 'V, S, M (un po\' di ragnatela di ragno)',
    description:
      'Riempi un cubo di 6 m di ragnatele appiccicose che rendono il terreno difficile. Ogni creatura che inizia il turno nell\'area o vi entra deve superare un TPS Destrezza o essere trattenuta finché rimane nell\'area. Una creatura trattenuta può usare la sua azione per un TPS Forza (CD incantesimo) per liberarsi. Le ragnatele sono infiammabili.',
  },
  {
    id: 'bloccare-persone',
    name: 'Bloccare Persone',
    level: 2,
    school: 'enchantment',
    classes: ['wizard', 'sorcerer', 'warlock', 'bard', 'cleric', 'druid'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione',
    range: '18 m',
    duration: 'Concentrazione, fino a 1 minuto',
    components: 'V, S, M (una piccola barra di ferro piatta)',
    description:
      'Scegli un umanoide che puoi vedere entro gittata. Il bersaglio deve superare un TPS Saggezza o essere paralizzato per la durata. Alla fine di ogni suo turno può ripetere il TS, terminando l\'effetto in caso di successo. Per ogni slot superiore al 2° puoi bersagliare un umanoide aggiuntivo.',
  },
  {
    id: 'arma-spirituale',
    name: 'Arma Spirituale',
    level: 2,
    school: 'evocation',
    classes: ['cleric', 'paladin'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione bonus',
    range: '18 m',
    duration: '1 minuto',
    components: 'V, S',
    description:
      'Evochi un\'arma spettrale fluttuante in uno spazio libero entro gittata. Come azione bonus puoi spostarla di 6 m e fare un attacco in mischia con incantesimo contro una creatura entro 1,5 m da essa, infliggendo 1d8 + modificatore da incantesimo danni da forza. Per ogni due livelli di slot superiori al 2° i danni aumentano di 1d8.',
  },
  {
    id: 'restaurazione-minore',
    name: 'Restaurazione Minore',
    level: 2,
    school: 'abjuration',
    classes: ['cleric', 'druid', 'bard', 'paladin', 'ranger'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: 'Tocco',
    duration: 'Istantanea',
    components: 'V, S',
    description:
      'Tocchi una creatura e poni fine a una malattia che la affligge oppure rimuovi una delle seguenti condizioni: accecato, avvelenato, paralizzato, sordastro.',
  },
  {
    id: 'preghiera-di-guarigione',
    name: 'Preghiera di Guarigione',
    level: 2,
    school: 'evocation',
    classes: ['cleric'],
    concentration: false,
    ritual: false,
    castingTime: '10 minuti',
    range: '9 m',
    duration: 'Istantanea',
    components: 'V',
    description:
      'Fino a sei creature a tua scelta entro gittata recuperano ciascuna 2d8 + modificatore di caratteristica da incantesimo punti ferita. Non funziona sui non-morti o sui costrutti. Per ogni slot superiore al 2° la guarigione aumenta di 1d8 per ciascun bersaglio.',
  },
  {
    id: 'suggestione',
    name: 'Suggestione',
    level: 2,
    school: 'enchantment',
    classes: ['wizard', 'sorcerer', 'warlock', 'bard'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione',
    range: '9 m',
    duration: 'Concentrazione, fino a 8 ore',
    components: 'V, M (la lingua di un serpente e un po\' di miele o un favo)',
    description:
      'Suggerisci una linea d\'azione formulata in modo plausibile a una creatura che puoi vedere entro gittata e che riesce a capirti. Il bersaglio deve superare un TPS Saggezza o seguire la suggestione al meglio delle sue capacità per la durata. L\'incantesimo termina se il bersaglio completa il compito o subisce danni.',
  },
  {
    id: 'oscurita',
    name: 'Oscurità',
    level: 2,
    school: 'evocation',
    classes: ['wizard', 'sorcerer', 'warlock'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione',
    range: '18 m',
    duration: 'Concentrazione, fino a 10 minuti',
    components: 'V, M (pelliccia di pipistrello e una goccia di catrame di pece o un pezzo di carbone)',
    description:
      'Oscurità magica si diffonde da un punto che scegli entro gittata in una sfera di 4,5 m di raggio. La visione del buio non penetra questa oscurità. Se il punto è un oggetto, l\'oscurità si muove con esso. Coprendo l\'oggetto si blocca l\'oscurità.',
  },
  {
    id: 'ingrandire-rimpicciolire',
    name: 'Ingrandire/Rimpicciolire',
    level: 2,
    school: 'transmutation',
    classes: ['wizard', 'sorcerer', 'bard'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione',
    range: '9 m',
    duration: 'Concentrazione, fino a 1 minuto',
    components: 'V, S, M (una presa di polvere di ferro)',
    description:
      'Fai ingrandire o rimpicciolire una creatura o un oggetto entro gittata. Ingrandendo: la taglia raddoppia, +1d4 danni con armi, vantaggio ai tiri di Forza. Rimpicciolendo: la taglia dimezza, -1d4 danni con armi, svantaggio ai tiri di Forza. Un bersaglio non consenziente può effettuare un TPS Costituzione per evitare l\'effetto.',
  },
  {
    id: 'raggio-di-luna',
    name: 'Raggio di Luna',
    level: 2,
    school: 'evocation',
    classes: ['druid'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione',
    range: '45 m',
    duration: 'Concentrazione, fino a 1 minuto',
    components: 'V, S, M (qualche seme di felce e una foglia d\'agrifoglio)',
    description:
      'Un raggio di luce lunare argentata si abbatte su un cilindro di 1,5 m di raggio e 12 m di altezza centrato su un punto entro gittata. Ogni creatura che entra nell\'area per la prima volta in un turno o vi inizia il turno deve superare un TPS Costituzione o subire 2d10 danni radianti (metà in caso di successo). Come azione bonus puoi spostare il raggio di 18 m. I danni aumentano di 1d10 per ogni slot superiore al 2°.',
  },
  {
    id: 'passare-senza-tracce',
    name: 'Passare Senza Lasciare Tracce',
    level: 2,
    school: 'abjuration',
    classes: ['druid', 'ranger'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione',
    range: 'Sé stesso',
    duration: 'Concentrazione, fino a 1 ora',
    components: 'V, S, M (cenere di un ramo di agrifoglio bruciato e un ciuffo di pelo di visone)',
    description:
      'Un velo di ombra e silenzio ti avvolge e si estende a tutte le creature amiche entro 9 m da te. Per la durata ogni creatura nell\'area ottiene +10 ai tiri di Furtività e non può essere tracciata da mezzi non magici.',
  },
  {
    id: 'silenzio',
    name: 'Silenzio',
    level: 2,
    school: 'illusion',
    classes: ['cleric', 'bard', 'ranger'],
    concentration: true,
    ritual: true,
    castingTime: '1 azione',
    range: '36 m',
    duration: 'Concentrazione, fino a 10 minuti',
    components: 'V, S',
    description:
      'Per la durata nessun suono può essere creato all\'interno di una sfera di 6 m di raggio centrata su un punto scelto entro gittata, né può passare attraverso di essa. Ogni creatura o oggetto totalmente all\'interno della sfera è immune ai danni da tuono, e le creature sono sorde finché si trovano all\'interno. Lanciare incantesimi con componente V è impossibile nell\'area.',
  },
  {
    id: 'zona-della-verita',
    name: 'Zona della Verità',
    level: 2,
    school: 'enchantment',
    classes: ['cleric', 'paladin'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '18 m',
    duration: '10 minuti',
    components: 'V, S',
    description:
      'Crei una zona magica che impedisce le bugie in una sfera di 4,5 m di raggio centrata su un punto entro gittata. Ogni creatura che entra nell\'area deve superare un TPS Carisma; in caso di fallimento non può pronunciare consapevolmente bugie per tutta la durata.',
  },

  // ─── LEVEL 3 ─────────────────────────────────────────────────────────────

  {
    id: 'palla-di-fuoco',
    name: 'Palla di Fuoco',
    level: 3,
    school: 'evocation',
    classes: ['wizard', 'sorcerer'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '45 m',
    duration: 'Istantanea',
    components: 'V, S, M (una piccola palla di guano di pipistrello e zolfo)',
    description:
      'Un bagliore infuocato emerge dal tuo dito verso un punto a tua scelta entro gittata e poi esplode con un rombo in una sfera di 6 m di raggio. Ogni creatura nell\'area deve effettuare un TPS Destrezza, subendo 8d6 danni da fuoco in caso di fallimento, o la metà in caso di successo. Per ogni slot superiore al 3° i danni aumentano di 1d6.',
  },
  {
    id: 'dardo-di-fulmine',
    name: 'Dardo di Fulmine',
    level: 3,
    school: 'evocation',
    classes: ['wizard', 'sorcerer', 'druid'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: 'Sé stesso (linea di 30 m)',
    duration: 'Istantanea',
    components: 'V, S, M (un po\' di pelo di pipistrello o ambra)',
    description:
      'Un fulmine di 30 m di lunghezza e 1,5 m di larghezza si scaglia dal tuo dito. Ogni creatura sulla linea deve effettuare un TPS Destrezza, subendo 8d6 danni da fulmine in caso di fallimento, o la metà in caso di successo. Il fulmine dà fuoco agli oggetti infiammabili che non indossa né trasporta nessuno. Per ogni slot superiore al 3° i danni aumentano di 1d6.',
  },
  {
    id: 'contrastare-magie',
    name: 'Contrastare Magie',
    level: 3,
    school: 'abjuration',
    classes: ['wizard', 'sorcerer', 'warlock', 'bard', 'cleric', 'druid', 'paladin'],
    concentration: false,
    ritual: false,
    castingTime: '1 reazione, che usi quando vedi una creatura entro 18 m da te lanciare un incantesimo',
    range: '18 m',
    duration: 'Istantanea',
    components: 'S',
    description:
      'Tenti di interrompere una creatura nell\'atto di lanciare un incantesimo. Se il livello dell\'incantesimo del bersaglio è pari o inferiore al livello dello slot usato, l\'incantesimo fallisce automaticamente. Se è di livello superiore, effettua una prova di caratteristica da incantesimo (CD 10 + livello dell\'incantesimo avversario); in caso di successo l\'incantesimo fallisce.',
  },
  {
    id: 'volare',
    name: 'Volare',
    level: 3,
    school: 'transmutation',
    classes: ['wizard', 'sorcerer', 'warlock', 'bard'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione',
    range: 'Tocco',
    duration: 'Concentrazione, fino a 10 minuti',
    components: 'V, S, M (una piuma d\'ala di qualche uccello)',
    description:
      'Tocchi una creatura consenziente. Il bersaglio acquisisce velocità di volo di 18 m per la durata. Quando l\'incantesimo termina, il bersaglio cade se è ancora in aria. Per ogni slot superiore al 3° puoi bersagliare una creatura aggiuntiva.',
  },
  {
    id: 'accelerare',
    name: 'Accelerare',
    level: 3,
    school: 'transmutation',
    classes: ['wizard', 'sorcerer'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione',
    range: '9 m',
    duration: 'Concentrazione, fino a 1 minuto',
    components: 'V, S, M (una goccia di melassa)',
    description:
      'Scegli una creatura consenziente entro gittata. Finché l\'incantesimo è attivo, la sua velocità raddoppia, ottiene +2 alla CA, vantaggio ai tiri salvezza di Destrezza e un\'azione aggiuntiva (solo per attaccare, Scatto, Disimpegnarsi, Nascondersi o Usare un oggetto) a ogni turno. Alla fine dell\'incantesimo la creatura è Rallentata per 1 turno.',
  },
  {
    id: 'dissolvere-magie',
    name: 'Dissolvere Magie',
    level: 3,
    school: 'abjuration',
    classes: ['wizard', 'sorcerer', 'warlock', 'bard', 'cleric', 'druid', 'paladin'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '18 m',
    duration: 'Istantanea',
    components: 'V, S',
    description:
      'Scegli una creatura, un oggetto o un effetto magico entro gittata. Qualsiasi incantesimo di 3° livello o inferiore sul bersaglio termina. Per ogni incantesimo di 4° livello o superiore, effettua una prova di caratteristica da incantesimo (CD 10 + livello dell\'incantesimo); in caso di successo l\'incantesimo termina.',
  },
  {
    id: 'animare-i-morti',
    name: 'Animare i Morti',
    level: 3,
    school: 'necromancy',
    classes: ['wizard', 'cleric'],
    concentration: false,
    ritual: false,
    castingTime: '1 minuto',
    range: '3 m',
    duration: '24 ore',
    components: 'V, S, M (una goccia di sangue, un po\' di carne e una polvere di ossa)',
    description:
      'Questo incantesimo crea un servitore non-morto. Scegli un mucchio di ossa o un cadavere di umanoide entro gittata: si alza come uno scheletro (da ossa) o uno zombie (da cadavere) con PF e statistiche appropriate. Per ogni slot superiore al 3° puoi animare due non-morti aggiuntivi.',
  },
  {
    id: 'ravvivare',
    name: 'Ravvivare',
    level: 3,
    school: 'conjuration',
    classes: ['cleric', 'paladin', 'bard'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: 'Tocco',
    duration: 'Istantanea',
    components: 'V, S, M (diamanti per un valore di 300 mo che vengono consumati)',
    description:
      'Riporti in vita una creatura che sia morta entro 1 minuto, purché non muoia di vecchiaia. La creatura torna con 1 PF. L\'incantesimo neutralizza qualsiasi veleno e guarisce le malattie che affliggevano la creatura al momento della morte.',
  },
  {
    id: 'guardiani-spirituali',
    name: 'Guardiani Spirituali',
    level: 3,
    school: 'conjuration',
    classes: ['cleric'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione',
    range: 'Sé stesso (raggio di 4,5 m)',
    duration: 'Concentrazione, fino a 10 minuti',
    components: 'V, S, M (un simbolo sacro)',
    description:
      'Evochi spiriti per proteggerti in un\'aura di 4,5 m. Puoi designare creature che l\'aura non influenza. Ogni altra creatura che entra nell\'aura per la prima volta in un turno o vi inizia il turno deve superare un TPS Saggezza o subire 3d8 danni radianti o necrotici (tua scelta); metà danni in caso di successo. Velocità dimezzata nell\'area. Per ogni slot superiore al 3° i danni aumentano di 1d8.',
  },
  {
    id: 'schema-ipnotico',
    name: 'Schema Ipnotico',
    level: 3,
    school: 'illusion',
    classes: ['wizard', 'sorcerer', 'warlock', 'bard'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione',
    range: '27 m',
    duration: 'Concentrazione, fino a 1 minuto',
    components: 'V, S, M (un bastoncino di incenso acceso o una piccola torcia di cristallo)',
    description:
      'Crei uno schema turbinante di colori in un cubo di 9 m entro gittata. Ogni creatura nell\'area deve superare un TPS Saggezza o essere affascinata per la durata. Mentre è affascinata, la creatura è incapacitata e ha velocità 0. L\'effetto termina per una creatura che riceve danni o se qualcuno usa un\'azione per scuoterla.',
  },
  {
    id: 'paura',
    name: 'Paura',
    level: 3,
    school: 'illusion',
    classes: ['wizard', 'sorcerer', 'warlock', 'bard'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione',
    range: 'Sé stesso (cono di 9 m)',
    duration: 'Concentrazione, fino a 1 minuto',
    components: 'V, S, M (una piuma bianca o un cuore di gallina)',
    description:
      'Proietti un\'immagine fantasmagorica dei peggiori timori di ogni creatura in un cono di 9 m. Ogni creatura nel cono deve superare un TPS Saggezza o lasciare cadere ciò che tiene ed essere spaventata per la durata; deve usare il movimento per allontanarsi da te. Alla fine di ogni suo turno può ripetere il TS.',
  },
  {
    id: 'invocare-fulmini',
    name: 'Invocare Fulmini',
    level: 3,
    school: 'conjuration',
    classes: ['druid'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione',
    range: '45 m',
    duration: 'Concentrazione, fino a 10 minuti',
    components: 'V, S',
    description:
      'Una nube tempestosa appare in un cilindro di 18 m di raggio e 3 m di altezza centrato su un punto entro gittata. Come azione chiami un fulmine su un punto sotto la nube: ogni creatura entro 1,5 m da quel punto deve superare un TPS Destrezza o subire 3d10 danni da fulmine (metà in caso di successo). Per ogni slot superiore al 3° i danni aumentano di 1d10.',
  },
  {
    id: 'luce-del-giorno',
    name: 'Luce del Giorno',
    level: 3,
    school: 'evocation',
    classes: ['cleric', 'druid', 'paladin', 'ranger', 'sorcerer'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '18 m',
    duration: '1 ora',
    components: 'V, S',
    description:
      'Una sfera di luce solare del diametro di 18 m si irradia da un punto scelto entro gittata. La sfera illumina con luce intensa l\'area e con luce fioca per ulteriori 18 m. L\'oscurità creata da incantesimi di livello inferiore al 3° viene dissolta nell\'area. Se il punto è su un oggetto, la luce si muove con esso; coprendo l\'oggetto si blocca la luce.',
  },
  {
    id: 'parola-guaritrice-di-massa',
    name: 'Parola Guaritrice di Massa',
    level: 3,
    school: 'evocation',
    classes: ['cleric', 'bard'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione bonus',
    range: '18 m',
    duration: 'Istantanea',
    components: 'V',
    description:
      'Fino a sei creature a tua scelta che puoi vedere entro gittata recuperano ciascuna 1d4 + modificatore di caratteristica da incantesimo punti ferita. Per ogni slot superiore al 3° la guarigione aumenta di 1d4 per ciascun bersaglio.',
  },
  {
    id: 'parlare-con-i-morti',
    name: 'Parlare con i Morti',
    level: 3,
    school: 'necromancy',
    classes: ['cleric', 'bard'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '3 m',
    duration: '10 minuti',
    components: 'V, S, M (incenso bruciante)',
    description:
      'Conferisci a un cadavere la facoltà di rispondere a cinque domande. Il cadavere deve avere ancora la bocca e non può essere un non-morto. Non è obbligato a dire la verità e la sua conoscenza si limita a ciò che sapeva in vita. Risposte di una o due parole.',
  },

  // ─── LEVEL 4 ─────────────────────────────────────────────────────────────

  {
    id: 'polimorfismo',
    name: 'Polimorfismo',
    level: 4,
    school: 'transmutation',
    classes: ['wizard', 'sorcerer', 'bard', 'druid'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione',
    range: '18 m',
    duration: 'Concentrazione, fino a 1 ora',
    components: 'V, S, M (un bozzolo di crisalide)',
    description:
      'Trasformi una creatura che puoi vedere entro gittata in una nuova forma. Una creatura non consenziente può effettuare un TPS Saggezza per evitare l\'effetto. Il bersaglio assume la forma di una bestia di sfida pari o inferiore al suo livello, con i PF di quella forma; se questi scendono a 0 la creatura torna alla forma originale con i PF che aveva prima.',
  },
  {
    id: 'invisibilita-superiore',
    name: 'Invisibilità Superiore',
    level: 4,
    school: 'illusion',
    classes: ['wizard', 'sorcerer', 'bard'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione',
    range: 'Tocco',
    duration: 'Concentrazione, fino a 1 minuto',
    components: 'V, S',
    description:
      'Tu o una creatura che tocchi diventate invisibili per la durata. Qualsiasi oggetto indossato o trasportato è invisibile. A differenza dell\'Invisibilità ordinaria, l\'effetto non termina se il bersaglio attacca o lancia incantesimi.',
  },
  {
    id: 'porta-dimensionale',
    name: 'Porta Dimensionale',
    level: 4,
    school: 'conjuration',
    classes: ['wizard', 'sorcerer', 'warlock', 'bard'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '150 m',
    duration: 'Istantanea',
    components: 'V',
    description:
      'Ti teletrasporti verso un luogo entro gittata. Puoi specificare la destinazione verbalmente (direzione e distanza) o indicando un luogo che conosci. Puoi portare con te una creatura Piccola o Umana consenziente o un oggetto che stai trasportando.',
  },
  {
    id: 'pelle-sassosa',
    name: 'Pelle Sassosa',
    level: 4,
    school: 'abjuration',
    classes: ['wizard', 'sorcerer', 'druid', 'ranger'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione',
    range: 'Tocco',
    duration: 'Concentrazione, fino a 1 ora',
    components: 'V, S, M (diamante in polvere per un valore di 100 mo che viene consumato)',
    description:
      'Tocchi una creatura consenziente il cui corpo diventa duro come pietra. Fino al termine della durata la creatura bersaglio ottiene resistenza ai danni non magici da contundente, perforante e tagliente.',
  },
  {
    id: 'bando',
    name: 'Bando',
    level: 4,
    school: 'abjuration',
    classes: ['cleric', 'paladin', 'sorcerer', 'warlock', 'wizard'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione',
    range: '18 m',
    duration: 'Concentrazione, fino a 1 minuto',
    components: 'V, S, M (un oggetto ripugnante al bersaglio)',
    description:
      'Tenti di mandare una creatura entro gittata in un altro piano. Il bersaglio deve superare un TPS Carisma. In caso di fallimento una creatura originaria del piano attuale è bandita in un demi-piano finché l\'incantesimo è attivo; una creatura di un altro piano torna a casa sua e vi rimane permanentemente se l\'incantesimo dura 1 minuto intero. Per ogni slot superiore al 4° puoi bersagliare una creatura aggiuntiva.',
  },
  {
    id: 'muro-di-fuoco',
    name: 'Muro di Fuoco',
    level: 4,
    school: 'evocation',
    classes: ['wizard', 'sorcerer', 'druid', 'paladin'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione',
    range: '36 m',
    duration: 'Concentrazione, fino a 1 minuto',
    components: 'V, S, M (un piccolo pezzo di fosforo)',
    description:
      'Crei un muro di fuoco su una superficie solida entro gittata. Il muro può essere lungo fino a 18 m, alto 6 m e spesso 30 cm oppure circolare di 6 m di diametro, alto 6 m e spesso 30 cm. Il muro è opaco e persiste per la durata. Ogni creatura che entra nel muro per la prima volta in un turno subisce 5d8 danni da fuoco. Per ogni slot superiore al 4° i danni aumentano di 1d8.',
  },
  {
    id: 'piaga',
    name: 'Piaga',
    level: 4,
    school: 'necromancy',
    classes: ['wizard', 'sorcerer', 'warlock', 'druid', 'ranger', 'cleric'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: 'Tocco',
    duration: 'Istantanea',
    components: 'V, S',
    description:
      'Effettua un attacco in mischia con incantesimo contro una creatura entro portata. In caso di colpo il bersaglio subisce 8d8 danni necrotici. Per ogni slot superiore al 4° i danni aumentano di 1d8.',
  },
  {
    id: 'protezione-dalla-morte',
    name: 'Protezione dalla Morte',
    level: 4,
    school: 'abjuration',
    classes: ['cleric', 'paladin'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: 'Tocco',
    duration: '8 ore',
    components: 'V, S',
    description:
      'Tocchi una creatura e la immunizzi dalla morte per la durata. La prima volta che scende a 0 PF durante la durata, rimane invece a 1 PF. L\'incantesimo termina dopo aver impedito questa prima morte.',
  },
  {
    id: 'divinazione',
    name: 'Divinazione',
    level: 4,
    school: 'divination',
    classes: ['cleric'],
    concentration: false,
    ritual: true,
    castingTime: '1 azione',
    range: 'Sé stesso',
    duration: 'Istantanea',
    components: 'V, S, M (incenso e offerta sacrificale adeguata alla divinità per un valore di 25 mo, consumati)',
    description:
      'Sei in comunione con il tuo dio che ti offre una guida veritiera su eventi che si verificheranno entro 7 giorni. Il DM risponde a una singola domanda con una risposta breve come "sì", "no", "forse" o una breve frase. Se poni più di una domanda in 7 giorni, ogni volta c\'è un 25% di probabilità di ricevere una risposta casuale e fuorviante.',
  },
  {
    id: 'tempesta-di-ghiaccio',
    name: 'Tempesta di Ghiaccio',
    level: 4,
    school: 'evocation',
    classes: ['wizard', 'sorcerer', 'druid'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '90 m',
    duration: 'Istantanea',
    components: 'V, S, M (un po\' di polvere di quarzo e acqua)',
    description:
      'Granelli di ghiaccio duri cadono in un cilindro di 6 m di raggio e 12 m di altezza centrato su un punto entro gittata. Ogni creatura nel cilindro subisce 2d8 danni da contundente e 4d6 danni da freddo (TPS Destrezza per la metà). Il suolo nell\'area è difficile fino alla fine del tuo prossimo turno. Per ogni slot superiore al 4° i danni da contundente aumentano di 1d8.',
  },

  // ─── LEVEL 5 ─────────────────────────────────────────────────────────────

  {
    id: 'cono-di-gelo',
    name: 'Cono di Gelo',
    level: 5,
    school: 'evocation',
    classes: ['wizard', 'sorcerer'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: 'Sé stesso (cono di 18 m)',
    duration: 'Istantanea',
    components: 'V, S, M (un piccolo cono cristallino)',
    description:
      'Un\'ondata di aria gelida si espande da te in un cono di 18 m. Ogni creatura nel cono deve effettuare un TPS Costituzione, subendo 8d8 danni da freddo in caso di fallimento, o la metà in caso di successo. Le creature che falliscono il TS vengono anche bloccate fino alla fine del tuo prossimo turno. Per ogni slot superiore al 5° i danni aumentano di 1d8.',
  },
  {
    id: 'scrutare',
    name: 'Scrutare',
    level: 5,
    school: 'divination',
    classes: ['wizard', 'bard', 'cleric', 'druid'],
    concentration: true,
    ritual: false,
    castingTime: '10 minuti',
    range: 'Sé stesso',
    duration: 'Concentrazione, fino a 10 minuti',
    components: 'V, S, M (uno specchio di cristallo, un catino pieno d\'acqua, o una sfera di cristallo del valore di 1.000 mo)',
    description:
      'Spii una creatura a tua scelta che si trova sullo stesso piano di esistenza. Il bersaglio deve effettuare un TPS Saggezza (modificato dalla tua conoscenza del bersaglio e dagli oggetti fisici correlati). In caso di fallimento, per la durata puoi vedere e sentire attraverso un sensore invisibile entro 3 m dal bersaglio.',
  },
  {
    id: 'cura-ferite-di-massa',
    name: 'Cura Ferite di Massa',
    level: 5,
    school: 'evocation',
    classes: ['cleric', 'druid', 'bard'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '18 m',
    duration: 'Istantanea',
    components: 'V, S',
    description:
      'Un\'ondata di energia guaritrice si diffonde da un punto scelto entro gittata: fino a sei creature entro 9 m da quel punto recuperano ciascuna 3d8 + modificatore da incantesimo PF. Non funziona sui non-morti o costrutti. Per ogni slot superiore al 5° la guarigione aumenta di 1d8 per ciascun bersaglio.',
  },
  {
    id: 'restaurazione-superiore',
    name: 'Restaurazione Superiore',
    level: 5,
    school: 'abjuration',
    classes: ['cleric', 'druid', 'bard'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: 'Tocco',
    duration: 'Istantanea',
    components: 'V, S, M (polvere di diamante per un valore di 100 mo, consumata)',
    description:
      'Infusi una creatura che tocchi con energia positiva per annullare un effetto debilitante. Puoi ridurre il punteggio di esaurimento del bersaglio di uno, oppure porre fine a uno dei seguenti effetti: un riduzione permanente di un punteggio di caratteristica, un riduzione massima dei PF, una maledizione o incantesimo di charm o petrificazione.',
  },
  {
    id: 'resuscitare-i-morti',
    name: 'Resuscitare i Morti',
    level: 5,
    school: 'necromancy',
    classes: ['cleric', 'paladin', 'bard'],
    concentration: false,
    ritual: false,
    castingTime: '1 ora',
    range: 'Tocco',
    duration: 'Istantanea',
    components: 'V, S, M (un diamante del valore di 500 mo, consumato)',
    description:
      'Riporti in vita una creatura morta entro 10 giorni, purché non sia morta di vecchiaia; il corpo deve essere ragionevolmente intero. La creatura torna con 1 PF; infligge -4 ai tiri per colpire, tiri salvezza e prove di caratteristica, malus che diminuisce di 1 ogni volta che completa un riposo lungo (fino a 4 riposi).',
  },
  {
    id: 'colpo-di-fiamma',
    name: 'Colpo di Fiamma',
    level: 5,
    school: 'evocation',
    classes: ['cleric'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '18 m',
    duration: 'Istantanea',
    components: 'V, S',
    description:
      'Una colonna verticale di fuoco divino e fiamme tuona e si abbatte su una creatura entro gittata in un cilindro di 3 m di raggio e 12 m di altezza. Il bersaglio e ogni altra creatura nel cilindro devono effettuare un TPS Destrezza. In caso di fallimento subiscono 4d6 danni da fuoco e 4d6 danni radianti, o la metà in caso di successo. Per ogni slot superiore al 5° ciascun tipo di danno aumenta di 1d6.',
  },
  {
    id: 'dominare-persone',
    name: 'Dominare Persone',
    level: 5,
    school: 'enchantment',
    classes: ['wizard', 'sorcerer', 'warlock', 'bard'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione',
    range: '18 m',
    duration: 'Concentrazione, fino a 1 minuto',
    components: 'V, S',
    description:
      'Tenti di dominare un umanoide che puoi vedere entro gittata. Il bersaglio deve superare un TPS Saggezza o essere affascinato da te per la durata. Puoi impartirgli comandi telepatici (nessuna azione necessaria) che esegue al meglio delle sue capacità. Se subisce danni può ripetere il TS. Per ogni slot superiore al 5° la durata aumenta: 10 minuti al 6°, 1 ora al 7°, 8 ore all\'8°.',
  },
  {
    id: 'bloccare-mostro',
    name: 'Bloccare Mostro',
    level: 5,
    school: 'enchantment',
    classes: ['wizard', 'sorcerer', 'warlock', 'bard'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione',
    range: '27 m',
    duration: 'Concentrazione, fino a 1 minuto',
    components: 'V, S, M (una piccola barra di ferro dritto)',
    description:
      'Scegli una creatura che puoi vedere entro gittata. Il bersaglio deve superare un TPS Saggezza o essere paralizzato per la durata. Funziona su qualsiasi tipo di creatura (non solo umanoidi). Alla fine di ogni suo turno può ripetere il TS. Per ogni slot superiore al 5° puoi bersagliare una creatura aggiuntiva.',
  },
  {
    id: 'nube-mortale',
    name: 'Nube Mortale',
    level: 5,
    school: 'conjuration',
    classes: ['wizard', 'sorcerer'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione',
    range: '27 m',
    duration: 'Concentrazione, fino a 10 minuti',
    components: 'V, S',
    description:
      'Crei una sfera di vapori giallo-verdi tossici di 6 m di raggio che oscura l\'area. Ogni creatura che si trova all\'interno all\'inizio del suo turno deve effettuare un TPS Costituzione, subendo 5d8 danni da veleno in caso di fallimento o la metà in caso di successo. La nube si sposta di 3 m nella direzione del vento (o a tua scelta) all\'inizio di ogni tuo turno.',
  },
  {
    id: 'muro-di-pietra',
    name: 'Muro di Pietra',
    level: 5,
    school: 'evocation',
    classes: ['wizard', 'sorcerer', 'druid'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione',
    range: '36 m',
    duration: 'Concentrazione, fino a 10 minuti',
    components: 'V, S, M (un piccolo granito)',
    description:
      'Fai sorgere un muro non magico di pietra solida da una superficie entro gittata. Il muro è spesso 15 cm, composto da pannelli da 3 m x 3 m, per un totale di pannelli pari a due volte il tuo livello da incantatore. Il muro non può essere creato su creature. Se lo è permanente puoi renderlo permanente con un\'azione.',
  },

  // ─── LEVEL 6 ─────────────────────────────────────────────────────────────

  {
    id: 'disintegrare',
    name: 'Disintegrare',
    level: 6,
    school: 'transmutation',
    classes: ['wizard', 'sorcerer'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '18 m',
    duration: 'Istantanea',
    components: 'V, S, M (un magnete e una polvere di ferro e polvere minerale)',
    description:
      'Lanci un raggio di luce verde verso un bersaglio entro gittata; effettua un attacco a distanza con incantesimo. In caso di colpo il bersaglio subisce 10d6 + 40 danni da forza. Se questi danni riducono il bersaglio a 0 PF, viene disintegrato (e solo un Vero Desiderio può riportarlo in vita). Per ogni slot superiore al 6° i danni aumentano di 3d6.',
  },
  {
    id: 'vista-autentica',
    name: 'Vista Autentica',
    level: 6,
    school: 'divination',
    classes: ['wizard', 'sorcerer', 'cleric', 'druid', 'bard'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione',
    range: 'Sé stesso',
    duration: 'Concentrazione, fino a 1 ora',
    components: 'V, S, M (goccia di olio di palma mescolata con succo di belladonna, unguento di fungo e grasso di verme, 250 mo)',
    description:
      'Hai visione magica pura per la durata. Entro 24 m vedi nel buio e nell\'invisibilità, percepisci automaticamente le illusioni visive e hai successo automatico ai TS contro di esse; vedi gli oggetti nascosti, percepisci la forma vera di trasformati o tramutati, e vedi nel Piano Etereo fino a 24 m.',
  },
  {
    id: 'folgore-a-catena',
    name: 'Folgore a Catena',
    level: 6,
    school: 'evocation',
    classes: ['wizard', 'sorcerer', 'druid'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '45 m',
    duration: 'Istantanea',
    components: 'V, S, M (un po\' di pelliccia, un pezzo di ambra o vetro, e tre denti d\'argento)',
    description:
      'Scegli fino a tre bersagli entro gittata; un fulmine li colpisce tutti. Ogni bersaglio deve effettuare un TPS Destrezza, subendo 10d8 danni da fulmine in caso di fallimento o la metà in caso di successo. Il fulmine salta poi su ulteriori bersagli entro 9 m (un bersaglio aggiuntivo per ogni slot superiore al 6°) con gli stessi effetti.',
  },
  {
    id: 'guarire',
    name: 'Guarire',
    level: 6,
    school: 'evocation',
    classes: ['cleric', 'druid'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: 'Tocco',
    duration: 'Istantanea',
    components: 'V, S',
    description:
      'Tocchi una creatura e scegli quanti PF recupera, fino a 70. L\'incantesimo pone fine anche a cecità, sordità e qualsiasi malattia che affligge il bersaglio. Non funziona sui non-morti o costrutti. Per ogni slot superiore al 6° la guarigione massima aumenta di 10.',
  },
  {
    id: 'suggestione-di-massa',
    name: 'Suggestione di Massa',
    level: 6,
    school: 'enchantment',
    classes: ['wizard', 'sorcerer', 'warlock', 'bard'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '18 m',
    duration: '24 ore',
    components: 'V, M (lingua di serpente, favo e olio di Citronella)',
    description:
      'Suggerisci una linea d\'azione a dodici o meno creature che puoi vedere entro gittata e che possono capirti. Ogni creatura deve superare un TPS Saggezza o seguire la suggestione per la durata. L\'incantesimo termina anticipatamente se il compito è portato a termine o se il bersaglio subisce danni. Per ogni slot superiore al 6° la durata raddoppia.',
  },
  {
    id: 'cerchio-della-morte',
    name: 'Cerchio della Morte',
    level: 6,
    school: 'necromancy',
    classes: ['wizard', 'sorcerer', 'warlock'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '45 m',
    duration: 'Istantanea',
    components: 'V, S, M (un\'ossa nera polverizzata)',
    description:
      'Un\'aura di energia necrotica esplode da un punto entro gittata in una sfera di 18 m di raggio. Ogni creatura nell\'area deve superare un TPS Costituzione, subendo 8d6 danni necrotici in caso di fallimento, o la metà in caso di successo. Per ogni slot superiore al 6° i danni aumentano di 2d6.',
  },
  {
    id: 'occhio-malefico',
    name: 'Occhio Malefico',
    level: 6,
    school: 'necromancy',
    classes: ['wizard', 'sorcerer', 'warlock', 'bard', 'cleric', 'druid'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione',
    range: '18 m',
    duration: 'Concentrazione, fino a 1 minuto',
    components: 'V, S',
    description:
      'I tuoi occhi diventano occhi di due divinità e lanci uno sguardo malvagio su una creatura entro gittata. Il bersaglio deve superare un TPS Saggezza o subire uno dei seguenti effetti a tua scelta per la durata: Addormentato (incapacitato, velocità 0), Atterrito (spaventato da te), Svenuto (incapacitato, cade prono se in piedi).',
  },

  // ─── LEVEL 7 ─────────────────────────────────────────────────────────────

  {
    id: 'teletrasporto',
    name: 'Teletrasporto',
    level: 7,
    school: 'conjuration',
    classes: ['wizard', 'sorcerer', 'bard'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '3 m',
    duration: 'Istantanea',
    components: 'V',
    description:
      'Teletrasporti te stesso e fino a otto creature consenzienti entro gittata verso una destinazione sul tuo stesso piano. La precisione del teletrasporto dipende dalla tua familiarità con il luogo (permanente, buona familiarità, visto brevemente, descrizione); un insuccesso può portarti a un luogo simile o simile oppure in un posto casuale.',
  },
  {
    id: 'inversione-di-gravita',
    name: 'Inversione di Gravità',
    level: 7,
    school: 'transmutation',
    classes: ['wizard', 'sorcerer', 'druid'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione',
    range: '90 m',
    duration: 'Concentrazione, fino a 1 minuto',
    components: 'V, S, M (un magnete di ferro e ferro da filatura)',
    description:
      'Tutte le creature e gli oggetti non fissati in un cilindro di 18 m di raggio e 90 m di altezza centrato su un punto entro gittata cadono verso l\'alto per la durata. Se una creatura colpisce il tetto del cilindro subisce danni da caduta. Alla fine dell\'incantesimo ricade verso il basso.',
  },
  {
    id: 'scroscio-prismatico',
    name: 'Scroscio Prismatico',
    level: 7,
    school: 'evocation',
    classes: ['wizard', 'sorcerer'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: 'Sé stesso (linea di 18 m)',
    duration: 'Istantanea',
    components: 'V, S',
    description:
      'Otto raggi di luce colorata scaturiscono dalla tua mano. Ogni raggio ha un colore diverso e un effetto differente (fuoco, fulmine, freddo, acido, veleno, disintegrazione, bando in un altro piano, o colpito da due raggi). Ogni creatura nella linea viene colpita da 1d8 raggi casuali e deve effettuare i tiri salvezza appropriati per ciascuno.',
  },
  {
    id: 'parola-divina',
    name: 'Parola Divina',
    level: 7,
    school: 'evocation',
    classes: ['cleric'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione bonus',
    range: '9 m',
    duration: 'Istantanea',
    components: 'V',
    description:
      'Pronunci una parola divina carica del potere che ha modellato il mondo. Ogni creatura ostile che puoi vedere entro gittata subisce un effetto basato sui suoi PF attuali: 50+ PF: sorda per 1 minuto; 30-49 PF: sorda e cieca per 10 minuti; 10-29 PF: sorda, cieca, stordita per 1 ora; 9 o meno PF: muore istantaneamente. Le creature extraplanari che falliscono un TPS Carisma vengono cacciate nel loro piano.',
  },
  {
    id: 'rigenerare',
    name: 'Rigenerare',
    level: 7,
    school: 'transmutation',
    classes: ['cleric', 'druid', 'bard'],
    concentration: false,
    ritual: false,
    castingTime: '1 minuto',
    range: 'Tocco',
    duration: '1 ora',
    components: 'V, S, M (un batuffolo di corteccia di muschio e gocce di argilla)',
    description:
      'Tocchi una creatura e stimoli la sua capacità rigenerativa. Il bersaglio recupera 4d8 + 15 PF all\'inizio dell\'incantesimo, poi recupera 1 PF all\'inizio di ogni suo turno per la durata. Per tutta la durata, le membra amputate vengono ricrescite nel corso dell\'ora.',
  },
  {
    id: 'resurrezione',
    name: 'Resurrezione',
    level: 7,
    school: 'necromancy',
    classes: ['cleric', 'bard'],
    concentration: false,
    ritual: false,
    castingTime: '1 ora',
    range: 'Tocco',
    duration: 'Istantanea',
    components: 'V, S, M (un diamante del valore di 1.000 mo, consumato)',
    description:
      'Riporti in vita una creatura morta entro 100 anni, purché non sia morta di vecchiaia. Il corpo deve essere ragionevolmente intero o ricreato durante il lancio. La creatura torna con tutti i PF. L\'incantesimo neutralizza veleni, malattie e guarisce i danni; le menomazioni fisiche vengono anch\'esse ripristinate.',
  },
  {
    id: 'gabbia-di-forza',
    name: 'Gabbia di Forza',
    level: 7,
    school: 'evocation',
    classes: ['wizard', 'warlock'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '27 m',
    duration: '1 ora',
    components: 'V, S, M (ruby dust worth 1.500 mo)',
    description:
      'Una gabbia invisibile di forza magica rinchiude un\'area a tua scelta entro gittata, in una delle seguenti forme: gabbia (fino a 6 m x 6 m x 3 m), scatola (fino a 3 m per lato) o sfera (fino a 3 m di diametro). Niente può passare fisicamente attraverso le pareti; gli incantesimi di teletrasporto o piano falliscono per chiunque all\'interno o all\'esterno.',
  },

  // ─── LEVEL 8 ─────────────────────────────────────────────────────────────

  {
    id: 'campo-antimagico',
    name: 'Campo Antimagico',
    level: 8,
    school: 'abjuration',
    classes: ['wizard', 'cleric'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione',
    range: 'Sé stesso (sfera di 3 m)',
    duration: 'Concentrazione, fino a 1 ora',
    components: 'V, S, M (pizzico di polvere o sabbia di ferro, più un po\' di gomma arabica)',
    description:
      'Emana un\'aura di energia antimagica in una sfera di 3 m di raggio che ti segue per la durata. Nessun incantesimo può essere lanciato all\'interno o attraverso la sfera, gli oggetti magici diventano ordinari, e tutte le magie attive vengono soppresse. I non-morti e le creature extraplanari convocate tramite magia non possono entrare nella sfera.',
  },
  {
    id: 'dominare-mostro',
    name: 'Dominare Mostro',
    level: 8,
    school: 'enchantment',
    classes: ['wizard', 'sorcerer', 'warlock', 'bard'],
    concentration: true,
    ritual: false,
    castingTime: '1 azione',
    range: '18 m',
    duration: 'Concentrazione, fino a 1 ora',
    components: 'V, S',
    description:
      'Tenti di dominare qualsiasi tipo di creatura entro gittata. Il bersaglio deve superare un TPS Saggezza o essere affascinato per la durata. Puoi dargli comandi telepatici come azione bonus. Se subisce danni ripete il TS. Alla fine della durata il bersaglio sa di essere stato dominato.',
  },
  {
    id: 'parola-di-potere-stordire',
    name: 'Parola di Potere: Stordire',
    level: 8,
    school: 'enchantment',
    classes: ['wizard', 'sorcerer', 'warlock', 'bard'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '18 m',
    duration: 'Istantanea',
    components: 'V',
    description:
      'Pronunci una parola di potere che stordisce una creatura visibile entro gittata. Se il bersaglio ha 150 PF o meno è stordito; altrimenti l\'incantesimo non ha effetto. Una creatura stordita deve effettuare un TPS Costituzione alla fine di ogni suo turno per terminare l\'effetto.',
  },
  {
    id: 'esplosione-solare',
    name: 'Esplosione Solare',
    level: 8,
    school: 'evocation',
    classes: ['cleric', 'druid', 'sorcerer'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '45 m',
    duration: 'Istantanea',
    components: 'V, S, M (fuoco e un pezzo di pietra solare)',
    description:
      'Brillante luce solare si irradia da un punto entro gittata in una sfera di 18 m di raggio. Ogni creatura nell\'area deve effettuare un TPS Costituzione, subendo 12d6 danni radianti in caso di fallimento (metà in caso di successo). Ogni creatura che fallisce è anche accecata fino al tuo prossimo turno. Annulla l\'oscurità magica nell\'area.',
  },
  {
    id: 'ottundere',
    name: 'Ottundere',
    level: 8,
    school: 'enchantment',
    classes: ['wizard', 'sorcerer', 'warlock', 'bard', 'druid'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '45 m',
    duration: '30 giorni',
    components: 'V, S',
    description:
      'Tenti di cancellare la memoria di una creatura entro gittata. Il bersaglio deve superare un TPS Intelligenza; in caso di fallimento, dimentica fino a 5 ore di propria esperienza a tua scelta, verificatesi nelle ultime 24 ore. La memoria viene riportata alla fine della durata o da Restaurazione Superiore.',
  },
  {
    id: 'mente-vuota',
    name: 'Mente Vuota',
    level: 8,
    school: 'abjuration',
    classes: ['wizard', 'bard'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: 'Tocco',
    duration: '24 ore',
    components: 'V, S',
    description:
      'Tocchi una creatura consenziente e la proteggi dalla lettura e dall\'alterazione mentale. Per la durata il bersaglio non può essere bersagliato da Detezione del Pensiero, Scrutare, o qualsiasi incantesimo divinatorio o trasmutatorio che influenzi la mente; ha anche immunità a qualsiasi effetto che percepisca le sue emozioni o i suoi pensieri.',
  },

  // ─── LEVEL 9 ─────────────────────────────────────────────────────────────

  {
    id: 'sciame-di-meteore',
    name: 'Sciame di Meteore',
    level: 9,
    school: 'evocation',
    classes: ['wizard', 'sorcerer'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '1.600 m',
    duration: 'Istantanea',
    components: 'V, S',
    description:
      'Meteore infuocate bombardano il terreno in quattro sfere di 13 m di raggio ciascuna, centrate su quattro punti entro gittata. Ogni creatura in una o più sfere deve effettuare un TPS Destrezza, subendo 20d6 danni da fuoco e 20d6 danni da contundente in caso di fallimento, o la metà in caso di successo. Le meteore danneggiano anche strutture e oggetti.',
  },
  {
    id: 'fermare-il-tempo',
    name: 'Fermare il Tempo',
    level: 9,
    school: 'transmutation',
    classes: ['wizard', 'sorcerer'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: 'Sé stesso',
    duration: 'Istantanea',
    components: 'V',
    description:
      'Fermi brevemente il flusso del tempo per tutti tranne te. Tira 1d4 + 1 per determinare il numero di turni aggiuntivi che esegui in sequenza, durante i quali le altre creature non possono muoversi né agire. L\'incantesimo termina anticipatamente se compi un\'azione che influisce su una creatura o su un oggetto che un\'altra creatura porta.',
  },
  {
    id: 'parola-di-potere-uccidere',
    name: 'Parola di Potere: Uccidere',
    level: 9,
    school: 'enchantment',
    classes: ['wizard', 'sorcerer', 'warlock', 'bard'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '18 m',
    duration: 'Istantanea',
    components: 'V',
    description:
      'Pronunci una parola di potere che uccide istantaneamente una creatura visibile entro gittata. Se il bersaglio ha 100 PF o meno muore all\'istante; altrimenti l\'incantesimo non ha effetto.',
  },
  {
    id: 'preveggenza',
    name: 'Preveggenza',
    level: 9,
    school: 'divination',
    classes: ['wizard', 'bard', 'druid'],
    concentration: false,
    ritual: false,
    castingTime: '1 minuto',
    range: 'Tocco',
    duration: '8 ore',
    components: 'V, S, M (piume di colibrì)',
    description:
      'Concedi a una creatura consenziente che tocchi la capacità di anticipare il futuro per la durata. Per tutta la durata il bersaglio non può essere sorpreso, ha vantaggio ai tiri per colpire, prove di caratteristica e tiri salvezza, e le creature hanno svantaggio ai tiri per colpire contro di lui.',
  },
  {
    id: 'cura-di-massa',
    name: 'Cura di Massa',
    level: 9,
    school: 'evocation',
    classes: ['cleric', 'druid'],
    concentration: false,
    ritual: false,
    castingTime: '1 azione',
    range: '18 m',
    duration: 'Istantanea',
    components: 'V, S',
    description:
      'Un\'ondata di energia guaritrice si propaga da te in ogni direzione. Ogni creatura entro gittata recupera 700 PF (suddivisi liberamente tra le creature come vuoi, senza superare i PF massimi di ciascuna). L\'incantesimo pone fine anche a cecità, sordità e qualsiasi malattia.',
  },
  {
    id: 'vera-resurrezione',
    name: 'Vera Resurrezione',
    level: 9,
    school: 'necromancy',
    classes: ['cleric', 'druid', 'bard'],
    concentration: false,
    ritual: false,
    castingTime: '1 ora',
    range: 'Tocco',
    duration: 'Istantanea',
    components: 'V, S, M (un\'agata che vale almeno 25.000 mo, consumata)',
    description:
      'Riporti in vita una creatura morta da non più di 200 anni che non sia morta di vecchiaia. La creatura torna con tutti i PF massimi e senza alcun debuff da ritorno in vita. Se il corpo è distrutto o non disponibile, puoi comunque lanciare l\'incantesimo nominando la creatura: ne viene creato un corpo nuovo e perfetto.',
  },
];
